/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RefsRouteImport } from './routes/refs'
import { Route as PackIdRouteImport } from './routes/pack.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefsRoute = RefsRouteImport.update({
  id: '/refs',
  path: '/refs',
  getParentRoute: () => rootRouteImport,
} as any)
const PackIdRoute = PackIdRouteImport.update({
  id: '/pack/$id',
  path: '/pack/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/refs': typeof RefsRoute
  '/pack/$id': typeof PackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/refs': typeof RefsRoute
  '/pack/$id': typeof PackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/refs': typeof RefsRoute
  '/pack/$id': typeof PackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/refs' | '/pack/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/refs' | '/pack/$id'
  id: '__root__' | '/' | '/refs' | '/pack/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RefsRoute: typeof RefsRoute
  PackIdRoute: typeof PackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refs': {
      id: '/refs'
      path: '/refs'
      fullPath: '/refs'
      preLoaderRoute: typeof RefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack/$id': {
      id: '/pack/$id'
      path: '/pack/$id'
      fullPath: '/pack/$id'
      preLoaderRoute: typeof PackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RefsRoute: RefsRoute,
  PackIdRoute: PackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
